# Judge parameters
name: Minosse
key: ApoChair2023!
problems_path: ./problems

# Server API parameters
config_check_api: http://localhost:3000/problem_versions
get_problem_config_api: http://localhost:3000/problems/config/{problem_id}
send_submission_result_api: http://localhost:3000/submissions/{submission_id}
send_total_submission_result_api: http://localhost:3000/submissions/{submission_id}/total

# RabbitMQ parameters
rabbitmq_host: rabbitmq
rabbitmq_user: apo
rabbitmq_pass: ApoChair2023!

# Execution parameters
execution_path: /tmp
languages:
  python:
    extension: .py
    run_command: "python3 {source_file}"
  c:
    extension: .c
    compile_command: "gcc {source_file} -o {executable}"
    run_command: "./{executable}"
  cpp:
    extension: .cpp
    compile_command: "g++ {source_file} -o {executable}"
    run_command: "./{executable}"
  rust:
    extension: .rs
    compile_command: "rustc {source_file}"
    run_command: "./{executable}"
  java:
    source_filename: Main
    extension: .java
    compile_command: "javac {source_file}"
    run_command: "java -Xmx256m {executable}"

loki_url: http://loki:3100/loki/api/v1/push
log_level: INFO
console_log: True
