services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=byteblitz
      - RABBITMQ_DEFAULT_PASS=asdoi23masdfn923
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - byteblitz

  minosse1:
    container_name: minosse1
    cap_add:
      - NET_ADMIN
      - NET_RAW
    image: byteblitz/minosse
    volumes:
      - ./config1.yml:/app/config.yml
    command: /app/venv/bin/python -u /app/main.py
    networks:
      - byteblitz

  minosse2:
    container_name: minosse2
    cap_add:
      - NET_ADMIN
      - NET_RAW
    image: byteblitz/minosse
    volumes:
      - ./config2.yml:/app/config.yml
    command: /app/venv/bin/python -u /app/main.py
    networks:
      - byteblitz

  minosse3:
    container_name: minosse3
    cap_add:
      - NET_ADMIN
      - NET_RAW
    image: byteblitz/minosse
    volumes:
      - ./config3.yml:/app/config.yml
    command: /app/venv/bin/python -u /app/main.py
    networks:
      - byteblitz

networks:
  byteblitz:
  bridge:
    driver: bridge